version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/build"
    labels:
      - "area/dependency"
      - "ok-to-test"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "quay.io/app-sre/boilerplate"
        # don't upgrade boilerplate via these means
